engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.coffee"
exclude_paths:
- "public/docs/"
