development:
  DB_HOST: localhost
  DB_DATABASE: database
  DB_USERNAME: user
  DB_PASSWORD: password
  DB_PORT: "5432"
  SECRET_KEY_BASE: abc123

test:
  DB_HOST: localhost
  DB_DATABASE: database
  DB_USERNAME: user
  DB_PASSWORD: password
  DB_PORT: "5432"
  SECRET_KEY_BASE: abc123

production:
  DB_HOST: localhost
  DB_DATABASE: database
  DB_USERNAME: user
  DB_PASSWORD: password
  DB_PORT: "5432"
  SECRET_KEY_BASE: abc123
