postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.fetch(Rails.env.to_sym).fetch(:db_host) %>
  database: <%= Rails.application.credentials.fetch(Rails.env.to_sym).fetch(:db_database) %>
  username: <%= Rails.application.credentials.fetch(Rails.env.to_sym).fetch(:db_username) %>
  password: <%= Rails.application.credentials.fetch(Rails.env.to_sym).fetch(:db_password) %>
  port: <%= Rails.application.credentials.fetch(Rails.env.to_sym).fetch(:db_port) %>

development:
  <<: *postgresql

test:
  <<: *postgresql

production:
  <<: *postgresql
