# Stars

Star.create([
  { name: 'Sun' },
  { name: 'Sirius' },
  { name: 'Caponus' },
  { name: 'Rigil Kentaurus' },
  { name: 'Arcturus' },
  { name: 'Vega' },
  { name: 'Capella' },
  { name: 'Rigel' },
  { name: 'Procyon' },
  { name: 'Achernar' },
  { name: 'Betelgeuse' },
  { name: 'Hadar' },
  { name: 'Altair' },
  { name: 'Acrux' },
  { name: 'Aldebaran' },
  { name: 'Antares' },
  { name: 'Spica' },
  { name: 'Pollux' },
  { name: 'Fomalhaut' },
  { name: 'Deneb' },
  { name: 'Mimosa' },
  { name: 'Regulus' },
  { name: 'Adhara' },
  { name: 'Shaula' },
  { name: 'Castor' },
  { name: 'Gacrux' },
  { name: 'Bellatrix' },
  { name: 'Elnath' },
  { name: 'Miaplacidus' },
  { name: 'Alnilam' }
])
